name: Release to PyPI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types: [ closed ]

permissions:
  contents: write
  id-token: write

jobs:
  # Job para crear release y publicar en PyPI
  release:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Necesario para tags
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    
    - name: Get version from pyproject.toml
      id: get_version
      run: |
        VERSION=$(python -c "import tomllib; print(tomllib.load(open('pyproject.toml', 'rb'))['project']['version'])" 2>/dev/null || python -c "import tomli; print(tomli.load(open('pyproject.toml', 'rb'))['project']['version'])")
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "tag=v$VERSION" >> $GITHUB_OUTPUT
    
    - name: Check if tag exists
      id: check_tag
      run: |
        if git rev-parse "refs/tags/${{ steps.get_version.outputs.tag }}" >/dev/null 2>&1; then
          echo "exists=true" >> $GITHUB_OUTPUT
        else
          echo "exists=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Create Git Tag
      if: steps.check_tag.outputs.exists == 'false'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git tag ${{ steps.get_version.outputs.tag }}
        git push origin ${{ steps.get_version.outputs.tag }}
    
    - name: Build package
      run: |
        python -m build
    
    - name: Check package
      run: |
        python -m twine check dist/*
    
    - name: Create GitHub Release
      if: steps.check_tag.outputs.exists == 'false'
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.get_version.outputs.tag }}
        release_name: Release ${{ steps.get_version.outputs.tag }}
        body: |
          ## 🚀 Release ${{ steps.get_version.outputs.version }}
          
          ### Changes in this release:
          - Automated release from master branch
          - Updated to version ${{ steps.get_version.outputs.version }}
          
          ### Installation:
          ```bash
          pip install mcp-open-client==${{ steps.get_version.outputs.version }}
          ```
          
          ### Quick Start:
          ```bash
          mcp-open-client
          ```
          
          See the [README](https://github.com/alejoair/mcp-open-client/blob/master/README.md) for full documentation.
        draft: false
        prerelease: false
    
    # - name: Publish to PyPI
    #   if: steps.check_tag.outputs.exists == 'false'
    #   uses: pypa/gh-action-pypi-publish@release/v1
    #   with:
    #     password: ${{ secrets.PYPI_API_TOKEN }}
    #     verbose: true
    
    - name: Notify success
      if: steps.check_tag.outputs.exists == 'false'
      run: |
        echo "🎉 Successfully released version ${{ steps.get_version.outputs.version }} to PyPI!"
        echo "📦 Package: https://pypi.org/project/mcp-open-client/${{ steps.get_version.outputs.version }}/"
        echo "🏷️ GitHub Release: https://github.com/alejoair/mcp-open-client/releases/tag/${{ steps.get_version.outputs.tag }}"
